### ISSUE TITLE
Learn's help articles link is broken

### ISSUE THREAD

**Issue by zkobrinsky** [learn-co-curriculum/first-mile-how-to-get-help#1]
https://learn.co/tracks/online-software-engineering-ft-first-mile/procedural-ruby/software-engineering/help.learn.co

"404: Page doesn't exist"

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
