### ISSUE TITLE
Learn's help articles link not working

### ISSUE THREAD

**Issue by peaceripple** [learn-co-curriculum/first-mile-how-to-get-help#2]
Hi,
When I clicked on the Learn's help articles link (tried several times) I got a 404 error message, "We're sorry - the page you're looking for doesn't exist."
FYI.
Thank you!
:-) Justine

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
